### PR TITLE
Add /boot on btrfs subvolume support

### PR DESCRIPTION
**Pull request by npmccallum**
Currently, the only thing blocking btrfs subvolume support for /boot in Fedora is grubby. All the other tooling supports it. This patch set teaches grubby how to respect /boot being on btrfs subvolumes. It accomplishes this by parsing /proc/mounts to determine the subvolume prefix.

Thanks to Gene Czarcinski, tests for this feature already exist. All tests pass (except for one test that is already failing in master).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Thank you so much for this! This is the only remaining bit to unblock efforts to make Anaconda smarter with Btrfs and complete integration for boot to snapshot!

**Comment by npmccallum** [comment]
FYI, these patches are now in Fedora rawhide:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1053784

**Comment by dustymabe** [comment]
> FYI, these patches are now in Fedora rawhide

Is that so they can be tested before merging this?

**Comment by vathpela** [comment]
Pushed to master.

**Pull request closed without merging**
